---
instance:
  name: spigot

driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: build
    run_list:
      - recipe[spigot::buildtools]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
  - name: default
    run_list:
    verifier:
      inspec_tests:
    attributes:
